# Generated by Django 5.0.6 on 2024-07-04 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_produits_auteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantite', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.produits')),
            ],
        ),
    ]
