# Generated by Django 5.0.6 on 2024-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_historique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Medicament', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('client', models.CharField(max_length=255)),
            ],
        ),
    ]
