# Generated by Django 5.0.6 on 2024-07-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='useremail',
            field=models.EmailField(default='default@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
        migrations.AddField(
            model_name='historique',
            name='useremail',
            field=models.EmailField(default='default@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='historique',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
    ]
