# Generated by Django 5.0.6 on 2024-07-31 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_commande_user_remove_historique_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='Medicament',
        ),
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.produits'),
        ),
    ]
