# Generated by Django 5.0.6 on 2024-08-10 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_vente_date_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.vente')),
            ],
        ),
    ]
