# Generated by Django 5.0.6 on 2024-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pharmacies/photos/')),
                ('nom', models.CharField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('proprietaire', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_ordre', models.CharField(blank=True, max_length=100, null=True)),
                ('licence_exploitation', models.FileField(blank=True, null=True, upload_to='pharmacie/autorisation/')),
                ('attestation_professionnelle', models.FileField(blank=True, null=True, upload_to='pharmacie/attestation/')),
            ],
        ),
    ]
